---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: '10.16.0'

inputs:
  - name: inspify-repository-chat-interface

outputs:
  - name: build
    path: inspify-repository-chat-interface/connect/chat-interface

caches:
  - path: inspify-repository-chat-interface/node_modules

run:
  path: /bin/sh
  args:
    - -exc
    - |
      BUILD_VERSION=$(cat inspify-repository-chat-interface/.git/short_ref)
      echo "Node Version: $(node --version)"
      echo "NPM Version: $(npm --version)"
      cd inspify-repository-chat-interface
        npm install --silent
        npm run test
        npm run build
      mkdir -p connect/chat-interface/$BUILD_VERSION/ && cp -r build connect/chat-interface/$BUILD_VERSION/